### ISSUE TITLE
JsInterop not working

### ISSUE THREAD

**Issue by Alexwhite3000** [tbroyer/gwt-maven-plugin#22] opened 2015-04-19 19:51 UTC
I can't get jsinterop working as per Thomas's advice in this thread:
https://groups.google.com/forum/#!topic/google-web-toolkit/9yvESx2hma0

Sample project:
https://github.com/Alexwhite3000/jsinterop-helloworld

**Comment by tbroyer** [comment] 2015-04-19 21:44
What exactly does not work?

From what I can see:

* you have a `<jsInteropMode>JS</jsInteropMode>` in `cupofjoe-client/pom.xml` that should be a `<compilerArg>` like you did with `<codeserverArgs>` in the root POM (you should probably put it in the root POM next to the `codeserverArgs` BTW). With only `<codeserverArgs>`, only `mvn gwt:codeserver` would use JsInterop, `mvn package` wouldn't (neither compiling your GWT app nor running GWT tests).
* `gwt:codeserver` works, but does not do anything with JsInterop. I unfortunately haven't yet played with JsInterop so I can't tell whether it's working as intended or not, but at least from the gwt-maven-plugin point of view, things are working. I'm closing this issue based on this; I'll reopen if needed.

**Closed by tbroyer** 2015-04-19 21:44 UTC

**Comment by Alexwhite3000** [comment] 2015-04-19 22:08
Hey Thomas,

What exactly does not work: I'm trying to export a symbol - MyFubar into JS, so that if I bring up Chrome Dev console it will show it as a variable. That doesn't seem to be happening here, even though others are able to do it with gradle based builds. (eg. https://github.com/christianbauer/gwt-polymer-jsinterop-test)

Regarding your suggestion, this is what I had in the root pom when you looked at it:
      <plugin>
        <groupId>net.ltgt.gwt.maven</groupId>
        <artifactId>gwt-maven-plugin</artifactId>
        <version>1.0-beta-2</version>
        <extensions>true</extensions>
        <configuration>
          <launcherDir>${project.build.directory}/gwt/launcherDir</launcherDir>
         <compilerArgs>
             <compileArg>-XjsInteropMode</compileArg>
             <compileArg>JS</compileArg>
         </compilerArgs>
            <codeserverArgs>
                <arg>-XjsInteropMode</arg>
                <arg>JS</arg>
            </codeserverArgs>
            <incremental>true</incremental>
            <jsInteropMode>JS</jsInteropMode>
        </configuration>
      </plugin>
 I'm trying to cover all my bases there. I think something isn't working correctly. mvn -X won't show me the codeserver invoke string either. :(

**Comment by tbroyer** [comment] 2015-04-19 22:32
It might just be that you're missing a `@JsNamespace`: https://github.com/christianbauer/gwt-polymer-jsinterop-test/blob/75775b7113a4aeff60d3de9435c708e4fc4a4549/src/main/java/sometest/client/package-info.java

The `Arguments:` and `Classpath:` lines show up for me with `mvn -X` just before the `Super Dev Mode starting up` line, and they contain `-XjsInteropMode JS`. Maybe try `mvn -X gwt:codeserver -Dgwt.logLevel=INFO` to lower the logging level of SDM while retaining debug level for Maven.

**Comment by ericbets** [comment] 2015-04-19 22:47
Heh, I still can't get it working. Thanks for the tip tho. At least I know now that it's definitely passing the arg.

**Comment by Alexwhite3000** [comment] 2015-04-19 22:49
I still can't get it working. Thanks for the tip though. It's definitely passing the arg.
