### ISSUE TITLE
Multiple modules in plugin configuration

### ISSUE THREAD

**Issue by Sonnayya** [tbroyer/gwt-maven-plugin#171] opened 2024-11-01 06:05 UTC
I use Eclipse for GWT development.
My GWT app has two modules: org.company.Common and org.company.Login.

Plugin in pom file:
```
	<plugin>
		<groupId>net.ltgt.gwt.maven</groupId>
		<artifactId>gwt-maven-plugin</artifactId>
		<configuration>
			<moduleName>org.company.Common</moduleName>
			<moduleName>org.company.Login</moduleName>
		</configuration>
	</plugin>
```

I run debug from Eclipse GWT plugin. 
In Tomcat webapp dir file Common.gwt.xml in war file exactly matches one in source project, but file Login.gwt.xml is very simple:

```
<module>
  <inherits name="com.google.gwt.core.Core"/>
  <source path="client"/>
  <source path="shared"/>
  <super-source path="super"/>
</module>

```

When I change position of module in configuration tag Login.gwt.xml is same source but Common.gwt.xml is simple.

**Comment by tbroyer** [comment] 2024-11-01 08:30
Duplicate of #57

**Closed by tbroyer** 2024-11-01 08:30 UTC

**Comment by Sonnayya** [comment] 2024-11-01 10:40
Thanks for reply. But I got the error.

```
			<plugin>
				<groupId>net.ltgt.gwt.maven</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>compile-common-module</id>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<moduleName>org.company.common.Common</moduleName>
							<moduleShortName>common</moduleShortName>
						</configuration>
					</execution>
					<execution>
						<id>compile-login-module</id>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<moduleName>org.company.login.Login</moduleName>
							<moduleShortName>login</moduleShortName>
						</configuration>
					</execution>
					<execution>
						<id>compile-app-module</id>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<moduleName>org.company.app.App</moduleName>
							<moduleShortName>app</moduleShortName>
						</configuration>
					</execution>
				</executions>
			</plugin>
```


Failed to execute mojo net.ltgt.gwt.maven:gwt-maven-plugin:1.1.0:generate-module {execution: default-generate-module} (net.ltgt.gwt.maven:gwt-maven-plugin:1.1.0:generate-module:default-generate-module:generate-resources)

org.eclipse.core.runtime.CoreException: Failed to execute mojo net.ltgt.gwt.maven:gwt-maven-plugin:1.1.0:generate-module {execution: default-generate-module}
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:404)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.lambda$2(MavenExecutionContext.java:355)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:458)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:339)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:354)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:57)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.lambda$2(MavenBuilderImpl.java:159)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:139)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:164)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:109)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:458)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:292)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:100)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:458)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:339)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:278)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.plugin.MojoExecutionException: Missing moduleName
	at net.ltgt.gwt.maven.GenerateModuleMojo.execute(GenerateModuleMojo.java:120)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:402)
	... 32 more
