### ISSUE TITLE
GWT Multimodule modulename specificaiton

### ISSUE THREAD

**Issue by panimozhi** [tbroyer/gwt-maven-plugin#149] opened 2021-09-01 16:20 UTC
@tbroyer I was able to able compile multi modules by using below specifications in eclipse

<moduleName>"com.xyz.web.Module1"	"com.xyz.web.Module2"</moduleName>

But the same pom is not compiling the module in the Jenkins build., could you please tell me how to enter multi module in net.ltgt.gwt.maven.

I think even if it has spaces between the modules, it's considering as single module., Kindly correct my understanding.

In the Jenkins logs.......
INFO] Loading inherited module 'com.xyz.web.Module1 com.xyz.web.Module2'
[INFO]    [ERROR] Invalid module name: 'com.xyz.web.Module1 com.xyz.web.Module2'

**Comment by tbroyer** [comment] 2021-09-01 17:39
Duplicate of #57

**Closed by tbroyer** 2021-09-01 17:39 UTC
