### ISSUE TITLE
rc7 devmode vs rc8 devmode

### ISSUE THREAD

**Issue by Waxolunist** [tbroyer/gwt-maven-plugin#95] opened 2017-10-09 13:58 UTC
When starting devmode from the reactor project with following line rc7 works and rc8 not:

    mvn gwt:devmode -pl <gwt-app-projectname> -am 

With rc8 I get following error:

    [WARNING] Error: Could not find or load main class com.google.gwt.dev.DevMode

The difference is in the classpath:

**rc7 classpath**:
```
<projectpath>/<gwt-app>/src/main/java:
<projectpath>/<gwt-app>/target/generated-sources/annotations:
<projectpath>/<gwt-lib>/src/main/java:
<projectpath>/<gwt-lib>/target/generated-sources/annotations:
<projectpath>/<gwt-app>/target/<gwt-app>/WEB-INF/classes:
<home>/.m2/repository/com/google/gwt/gwt-dev/2.8.1/gwt-dev-2.8.1.jar:<home>/.m2/repository/com/google/code/gson/gson/2.6.2/gson-2.6.2.jar:
<all other maven deps>
```

**rc8 classpath**:
```
<projectpath>/<gwt-app>/src/main/java:
<projectpath>/<gwt-app>/target/generated-sources/annotations:
<projectpath>/<gwt-lib>/src/main/java:
<projectpath>/<gwt-lib>/target/generated-sources/annotations:
<projectpath>/<gwt-app>/target/<gwt-app>/WEB-INF/classes:
```

In rc8 all maven jars are missing.

**Comment by tbroyer** [comment] 2017-10-09 14:09
Could it be a dupe of #91? I haven't gotten to release a rc9 yet.

**Comment by Waxolunist** [comment] 2017-10-10 11:54
That is maybe the same. I just tested with 1.0-SNAPSHOT and I get following error

```
[ERROR] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-SNAPSHOT:add-super-sources (default-add-super-sources) on project gwt-common: Execution default-add-super-sources of goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-SNAPSHOT:add-super-sources failed: An API incompatibility was encountered while executing net.ltgt.gwt.maven:gwt-maven-plugin:1.0-SNAPSHOT:add-super-sources: java.lang.NoSuchMethodError: org.codehaus.plexus.util.StringUtils.isBlank(Ljava/lang/String;)Z
```

**Comment by tbroyer** [comment] 2017-10-10 13:50
Could you run Maven with debug logs (`mvn -X`) and isolate the portion where it populates the _class realm_ for the plugin? (should begin with a line like _“[DEBUG] Populating class realm plugin>net.ltgt.gwt.maven:gwt-maven-plugin:1.0-SNAPSHOT”_, the lines above should be in "tree" view, the lines below the flat list of dependencies added to the plugin classloader)

**Comment by Waxolunist** [comment] 2017-10-10 15:34
I ran now the devmode with -X option on java 8 and maven 3.3.9:

```
Populating class realm extension>net.ltgt.gwt.maven:gwt-maven-plugin:1.0-SNAPSHOT
[DEBUG]   Included: net.ltgt.gwt.maven:gwt-maven-plugin:jar:1.0-SNAPSHOT
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:1.1
[DEBUG] Extension realms for project com.payolution:gwt-common:gwt-lib:1.10.0-SNAPSHOT: [ClassRealm[extension>net.ltgt.gwt.maven:gwt-maven-plugin:1.0-SNAPSHOT, parent: sun.misc.Launcher$AppClassLoader@5c647e05]]
[DEBUG] Created new class realm project>com.payolution:gwt-common:1.10.0-SNAPSHOT
[DEBUG] Populating class realm project>com.payolution:gwt-common:1.10.0-SNAPSHOT
[DEBUG] Looking up lifecyle mappings for packaging gwt-lib from ClassRealm[project>com.payolution:gwt-common:1.10.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]
[DEBUG] Extension realms for project com.payolution:collection-portal-ui:gwt-app:1.6.0-SNAPSHOT: [ClassRealm[extension>net.ltgt.gwt.maven:gwt-maven-plugin:1.0-SNAPSHOT, parent: sun.misc.Launcher$AppClassLoader@5c647e05]]
[DEBUG] Looking up lifecyle mappings for packaging gwt-app from ClassRealm[project>com.payolution:gwt-common:1.10.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]
[INFO] ------------------------------------------------------------------------
```

**Comment by tbroyer** [comment] 2017-10-10 18:07
OK, so, plexus-utils 1.1 is automatically added by Maven when it doesn't find plexus-utils as a dependency of the plugin (backwards compat' with Maven 1 (sic!)). This means your POM for the gwt-maven-plugin is corrupt. Clean your local repo and/or force redownload with `-U` (might not redownload, might only check for new version, and thus keep your corrupt POM)

**Closed by tbroyer** 2017-10-10 18:07 UTC

**Comment by Waxolunist** [comment] 2017-10-11 13:18
You are right. I was missing the pom file. Somehow nexus did not download the pom file.
I can now confirm, that devmode is working for me with rc7 and 1.0-SNAPSHOT but not rc8.
I will now use the snapshot version and as soon as rc9 is released will use that one.
Thank you for your help.
